### ISSUE TITLE
D3Net training: CUDA out of memory

### ISSUE THREAD

**Issue by lyghter** [yuzhouhe2000/Music_Source_Separator#2]
I tried to train D3Net on the training part of MUSDB18-HQ with batch_size=1, but got the error: 

```
RuntimeError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 0; 23.88 GiB total capacity; 22.79 GiB already allocated; 44.50 MiB free; 23.12 GiB reserved in total by PyTorch)
```

**Comment by yuzhouhe2000** [comment]
D3Net consumes significantly larger memory than the other net. I tried the original set up in the paper, and it takes about 20 GB CUDA memory with a batch size = 1. Maybe reduce your batch size or choose a smaller D3Net.
